DOMAIN                  = 'irrigationprogram'
SWITCH_ID_FORMAT        = 'switch' + '.{}'

ATTR_RAIN_SENSOR        = 'rain_sensor'
ATTR_IRRIGATION_ON      = 'irrigation_on'
ATTR_START              = 'start_time'
ATTR_IGNORE_RAIN_SENSOR = 'ignore_rain_sensor'
ATTR_SHOW_CONFIG        = 'show_config'
ATTR_RUN_FREQ           = 'run_freq'
ATTR_FRIENDLY_NAME      = 'friendly_name'
ATTR_REMAINING          = 'remaining'
ATTR_REPEAT             = 'repeat'
ATTR_RUNTIME            = 'runtime'
ATTR_WAIT               = 'wait'
ATTR_DELAY              = 'inter_zone_delay'
ATTR_FLOW_SENSOR        = 'flow_sensor'
ATTR_WATER              = 'water'
ATTR_WATER_ADJUST       = 'water_adjustment'
ATTR_ZONES              = 'zones'
ATTR_ZONE               = 'zone'
ATTR_ZONE_GROUP         = 'zone_group'
ATTR_PUMP               = 'pump'
ATTR_LAST_RAN           = 'last_ran'
ATTR_SWITCHES           = 'switches'
ATTR_MONITOR_CONTROLLER = 'controller_monitor'
ATTR_DISABLE_ZONE       = 'disable_zone'
ATTR_ENABLE_ZONE        = 'enable_zone'
ATTR_RESET              = 'reset'
ATTR_WATER_MIN          = 'water_min'
ATTR_WATER_MAX          = 'water_max'
ATTR_WATER_STEP         = 'water_step'


CONST_ENTITY            = 'entity_id'
CONST_SWITCH            = 'switch'

DFLT_IRRIGATION_ON      = 'Enable irrigation'
DFLT_START              = 'Start time'
DFLT_IGNORE_RAIN_SENSOR = 'Ignore rain sensor'
DFLT_SHOW_CONFIG        = 'Show configuration'
DFLT_REPEAT             = 'Repeat'
DFLT_WATER              = 'Water'
DFLT_WAIT               = 'Wait'
DFLT_DELAY              = 'Inter zone delay'
DFLT_FLOW_SENSOR        = 'Flow sensor'
DFLT_WATER_ADJUST       = 'Water adjustment'
DFLT_ENABLE_ZONE        = 'Enable zone'
DFLT_ZONE_GROUP         = 'Zone group' #zones that run concurrently
DFLT_RUN_FREQ           = 'Frequency'

DFLT_WATER_INITIAL_T    = 1
DFLT_WATER_MAX_T        = 30
DFLT_WATER_STEP_T       = 1
DFLT_WATER_INITIAL_M    = 10
DFLT_WATER_MAX_M        = 1200
DFLT_WATER_STEP_M       = 10
DFLT_WATER_INITIAL_I    = 5
DFLT_WATER_MAX_I        = 350
DFLT_WATER_STEP_I       = 5
DFLT_WAIT_MAX           = 30
DFLT_REPEAT_MAX         = 30
#DFLT_REMAINING          = 'Remaining'
#DFLT_RUNTIME            = 'Runtime'
#DFLT_MONITOR_CONTROLLER = 'Controller monitor'
#DFLT_DISABLE_ZONE       = 'disable_zone'
